development:
  dialect: postgres
  database: sbma
  user: postgres
  password: Science@1992
  host: localhost
  pool: 5

production:
  dialect: postgres
  database: sbma
  user: postgres.ilmlvurperawqzzrqbye
  password: 0904Sc!ence@!992$
  host: aws-0-eu-central-1.pooler.supabase.com
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_test"}}

prod:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/myapp_production"}}